const Game = {
model:{
    CAVALLINO_288_GTO = "cavallino_288_gto",
    KAITO_RX_VIPER = "kaito_rx_viper",
    MERIDIAN_WILDREACH = "meridian_wildreach",
    IMPERIA_911 = "imperia_911",
    MERIDIAN_EMISSARY = "meridian_emissary",
    STRATA_G150 = "strata_g150",
    IMPERIA_TURBO = "imperia_turbo",
    NATIONAUTO_CORRADO_VR6 = "nationauto_corrado_vr6",
    ROUGHYEAR_VERMIN_VOYAGER = "roughyear_vermin_voyager",
    FOOD_TRUCK = "food_truck",
    NATIONAUTO_STRONGUARD_142 = "nationauto_stronguard_142",
    KAITO_NIGHTWEAVER_86 = "kaito_nightweaver_86",
    KAITO_AE86_RS = "kaito_ae86_rs",
    IMPERIA_720S = "imperia_720s",
    DI_WAREHOUSE_FORKLIFT = "di_warehouse_forklift",
    KEI_CLIPPER = "kei_clipper",
    CAVALLINO_SC_25 = "cavallino_sc_25",
    IMPERIA_911_RS = "imperia_911_rs"
},
wrap:{
    WHITE = "white",
    INFERNO_RED = "inferno_red",
    BLOODHOUND_RED = "bloodhound_red",
    RADIANT_ORANGE = "radiant_orange",
    ELECTRIC_YELLOW = "electric_yellow",
    MAELSTROM_BLUE = "maelstrom_blue",
    VORTEX_BLUE = "vortex_blue",
    PHANTOM_PURPLE = "phantom_purple",
    ROYAL_PINK = "royal_pink",
    EMERALD_GREEN = "emerald_green",
    DESERT_BEIGE = "desert_beige",
    CHECKER = "checker",
    PLAID = "plaid",
    FADE = "fade",
    DEEP_SPACE = "deep_space",
    RAINBOW = "rainbow",
    HEXAGON = "hexagon",
    NEON_ARC = "neon_arc",
    LEOPARD_PRINT = "leopard_print",
    MOLTEN_LAVA = "molten_lava",
    SOLAR_CELL = "solar_cell",
    FRESH_CUT = "fresh_cut",
    ZEBRA_PRINT = "zebra_print",
    PORCELAIN = "porcelain",
    CHERRY_BLOSSOM = "cherry_blossom",
    REGAL_RED = "regal_red",
    DRIFTPAT = "driftpat",
    MARBLE = "marble",
    RUST_BUCKET = "rust_bucket",
    BACKSTREET_GRAFFITI = "backstreet_graffiti",
    MANGA_PANEL = "manga_panel",
    CHROME = "chrome",
    SPLATTER = "splatter"
},
tire:{
    CAVALLINO_PILOT_S5 = "cavallino_pilot_s5_tire",
    CIRCULAR_SAW = "circular_saw_tire",
    CLASSIC = "classic_tire",
    DI_D0_HIGH_PERFORMANCE = "di_d0_high_performance_tire",
    DI_EXPERIMENTAL_SQUARE = "di_experimental_square_tire",
    DI_AIRLESS = "di_airless_tire",
    KAITO_SPORT_3X = "kaito_sport_3x_tire",
    MERIDIAN_SNOW_LANDER = "meridian_snow_lander_tire",
    NATIONAUTO_STANDARD_AT = "nationauto_standard_at_tire",
    NATIONAUTO_TRAILBLAZER = "nationauto_trailblazer_tire",
    OLD_MAN_JOHNSONS_WAGON_WHEEL = "old_man_johnsons_wagon_wheel",
    ROUGHYEAR_ARMORED_SPIKE = "roughyear_armored_spike_tire",
    ROUGHYEAR_DAYBREAK_HT = "roughyear_daybreak_ht_tire",
    ROUGHYEAR_FALCON = "roughyear_falcon_tire",
    ROUGHYEAR_SPHERE = "roughyear_sphere_tire",
    PIZZA = "pizza_tire",
    HOVER = "hover_tire",
    JACK_O_TIRE = "jack_o_tire"
}
}